# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - all_group_controller

  all_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - chassis_joint
      - left_shoulder_joint
      - left_rotator_joint
      - left_elbow_joint
      - left_grip_joint
      - left_thumb_joint
      - left_paw_joint
      - neck_yaw_joint
      - left_neck_joint
      - right_neck_joint
      - right_shoulder_joint
      - right_rotator_joint
      - right_elbow_joint
      - right_grip_joint
      - right_thumb_joint
      - right_paw_joint