# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    all_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

all_group_controller:
  ros__parameters:
    joints:
      - chassis_joint
      - left_shoulder_joint
      - left_rotator_joint
      - left_elbow_joint
      - left_grip_joint
      - left_thumb_joint
      - left_paw_joint
      - neck_yaw_joint
      - left_neck_joint
      - right_neck_joint
      - right_shoulder_joint
      - right_rotator_joint
      - right_elbow_joint
      - right_grip_joint
      - right_thumb_joint
      - right_paw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position